# Currently Deprecated
Speed_Multiplier: 1.5

# The number your current speed is divided by when decelerating with the rod.
Speed_Divisor: 10

# The static speed for the set_speed command
Static_Speed: 5.0

# Sets the command options for the following: (Must be NONE, ACCELERATE, DECELERATE, SET_SPEED, FLAK, BOMB)
AccRod:
  MaxSpeed: 2
  BomberMaxSpeed: 1.5
  RateOfAccel: .25
  Delay: 3
  Right_Click: NONE
  Left_Click: SET_SPEED

FlakSnowball:
  Left_Click: NONE
  Right_Click: FLAK
  Interval: .3
  Radius: 5
  ElytraDamage: 108

BombBay:
  ReloadTime: 6
  BombDropDelay: 8   # This is in ticks, so multiply number of seconds by 10
  ExplodeSize: 4.5
  Capacity: 5
  Left_Click: NONE
  Right_Click: BOMB

AircraftGun:
  Left_Click: NONE
  Right_Click: FIRE_GUN
  Damage: 2